# Generated by Django 6.0.3 on 2026-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_exam_teacher_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questin_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('theory', 'Theory'), ('true_false', 'True/False')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('self_assessment', 'Self-Assessment'), ('test', 'Test'), ('exam', 'Exam')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=1),
        ),
    ]

