# Generated by Django 6.0.3 on 2026-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_lecturenote_mediaresource_selfassessmentattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
