# Generated by Django 6.0.3 on 2026-05-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
